"""Canonical assembly: research governance above one RC11.7 execution data plane."""
from pathlib import Path
from kvcontinual.execution.source import SourceSegmentStore
from kvcontinual.execution.cache.persistent import PersistentExecutionArtifactStore
from kvcontinual.execution.runtime import ReconstructionRuntime
from kvcontinual.execution.types import ReconstructionMode
from kvcontinual.execution.qualification_bundle import verify_qualification_bundle
from kvcontinual.execution.macos_qualification_preflight import run_macos_qualification_preflight
from kvcontinual.execution.hardware_qualification import detect_hardware_runtime_fingerprint
from minagi.egai import (EvidenceLedger, SkillRepository, BeliefRepository,
                         CognitivePlane, LearningPlane, PromotionAuthority,
                         ImprovementLedger, IndependentQualificationGate)


class GovernedSystem:
    """No signer is generated by the cognitive or learning plane.

    The external promotion operator supplies the research verifier and signer.
    Acceleration starts disabled and requires a content-bound, signed target-Mac
    qualification and deployment binding. Research qualification cannot enable it.
    """
    def __init__(self, root, backend, *, research_verifier, promotion_signer, budget=None):
        self.root=Path(root); self.root.mkdir(parents=True,exist_ok=True)
        self.sources=SourceSegmentStore(str(self.root/'source.sqlite3'))
        self.artifacts=PersistentExecutionArtifactStore(self.root/'execution',budget=budget)
        self.execution=ReconstructionRuntime(self.sources,self.artifacts,backend)
        self.evidence=EvidenceLedger(self.root/'evidence')
        self.skills=SkillRepository(self.root/'skills')
        self.beliefs=BeliefRepository(self.root/'beliefs')
        self.cognitive=CognitivePlane(evidence=self.evidence,skills=self.skills,beliefs=self.beliefs)
        self.learning=LearningPlane(skills=self.skills,beliefs=self.beliefs)
        self.promotion=PromotionAuthority(gate=IndependentQualificationGate(chain_verifier=research_verifier),
            improvement_ledger=ImprovementLedger(self.root/'improvements.jsonl'),signer=promotion_signer)
        self._qualification=None

    def bind_target_qualification(self, *, identity, bundle, receipt, verifier,
                                  certificate, deployment_binding, backend_fingerprint,
                                  release_manifest_digest, qualification_ledger_head,
                                  qualification_suite_digest):
        # A probe or a research score is never sufficient for execution authorization.
        preflight=run_macos_qualification_preflight(backend_fingerprint=backend_fingerprint)
        preflight.validate()
        if bundle.get('schema_version')!=2 or not verify_qualification_bundle(bundle):
            raise PermissionError('valid content-bound execution qualification required')
        if bundle['execution_identity_digest']!=identity.digest or bundle['runtime_build_digest']!=release_manifest_digest:
            raise PermissionError('qualification execution/release identity mismatch')
        hardware=detect_hardware_runtime_fingerprint(backend_fingerprint=backend_fingerprint)
        certificate.validate(identity=identity,backend_fingerprint=backend_fingerprint,
            hardware_runtime_digest=hardware.digest,release_manifest_digest=release_manifest_digest,
            qualification_suite_digest=qualification_suite_digest,qualification_ledger_head=qualification_ledger_head)
        deployment_binding.validate_certificate(certificate)
        signed_body={'schema':'mini-agi-target-deployment-v1','bundle':bundle,
                     'certificate_digest':certificate.certificate_digest,
                     'deployment_binding_digest':deployment_binding.binding_digest,
                     'hardware_runtime_digest':hardware.digest}
        if not verifier.verify(receipt,expected_body=signed_body):
            raise PermissionError('independent execution/deployment qualification signature required')
        self._qualification=(identity.digest,backend_fingerprint,release_manifest_digest,
                             signed_body,receipt,verifier,hardware.digest)

    def reconstruct(self, segment_ids, identity, mode=ReconstructionMode.EXACT, **kwargs):
        q=self._qualification
        if q is None or q[0]!=identity.digest:
            mode=ReconstructionMode.EXACT
        else:
            # Revocation and live host drift are checked again for each request.
            hardware=detect_hardware_runtime_fingerprint(backend_fingerprint=q[1])
            if hardware.digest!=q[6] or not q[5].verify(q[4],expected_body=q[3]):
                self._qualification=None
                mode=ReconstructionMode.EXACT
        return self.execution.reconstruct(segment_ids,identity,mode,**kwargs)

    def close(self):
        self.artifacts.close()
        self.sources.conn.close()
