#!/usr/bin/env python3
"""Provision the v16.5 campaign authority plane for a storage root.

Creates five role keys under <storage>/.keys/<role>.pem and writes
<storage>/trust_root.json listing each role's public identity:

    plan                preregisters immutable experiments
    execution_witness   attests worker executions (receipts)
    evaluation          attests observed predictions and metrics
    qualification       applies frozen acceptance criteria
    promotion           authorizes deployment of qualified artifacts

DEPLOYMENT NOTE: generating all five keys in one step on one host is a
development convenience for the Colab harness — it provides the
cryptographic plumbing but NOT the operational separation. In a real
deployment each role key should be generated by its own operator under
its own OS identity/host, and only the public records exchanged into the
shared trust root. The qualification and promotion keys in particular
should never live on the training worker.
"""
from __future__ import annotations

import argparse
import base64
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src-python"))

from egai.common.crypto import Ed25519Signer
from minagi.v161.authority import (AUTHORITY_ROLES, AuthorityLedger,
                                   AuthorityRecord, AuthorityRegistry,
                                   provision_role)


def _record(role: str, signer: Ed25519Signer,
            status: str = "active") -> dict:
    return {"role": role, "key_id": signer.key_id,
            "public_key_b64": base64.b64encode(
                signer.public_bytes()).decode(),
            "status": status, "not_before": "", "not_after": ""}


def _write_trust(path, records: list[dict]):
    doc = {"schema": "mini-agi-v16.5-authority-trust-root-v1",
           "authorities": records}
    Path(path).write_text(json.dumps(doc, indent=2, sort_keys=True))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--storage", required=True,
                    help="campaign storage root (holds .keys/, "
                         "trust_root.json, AUTHORITY_LEDGER.jsonl)")
    ap.add_argument("--revoke", default=None,
                    help="revoke a role's current key and provision a "
                         "fresh identity (old record stays, marked "
                         "revoked — key-lifecycle, not silent rewrite)")
    args = ap.parse_args()

    storage = Path(args.storage)
    keys_dir = storage / ".keys"
    trust_path = storage / "trust_root.json"

    if args.revoke:
        if args.revoke not in AUTHORITY_ROLES:
            raise SystemExit(f"unknown role: {args.revoke}")
        if not trust_path.is_file():
            raise SystemExit("no trust root to revoke under")
        doc = json.loads(trust_path.read_text())
        for a in doc["authorities"]:
            if a["role"] == args.revoke and a["status"] == "active":
                a["status"] = "revoked"
        old = keys_dir / f"{args.revoke}.pem"
        if old.is_file():
            old.rename(old.with_suffix(f".revoked-{args.revoke}.pem"))
        fresh = provision_role(keys_dir, args.revoke)
        doc["authorities"].append(_record(args.revoke, fresh))
        _write_trust(trust_path, doc["authorities"])
        print(json.dumps({"status": "revoked+reprovisioned",
                          "role": args.revoke,
                          "new_key_id": fresh.key_id}, indent=2))
        return 0

    records = []
    existing = json.loads(trust_path.read_text())["authorities"] \
        if trust_path.is_file() else []
    records.extend(existing)
    for role in AUTHORITY_ROLES:
        signer = provision_role(keys_dir, role)
        if not any(a["role"] == role and a["key_id"] == signer.key_id
                   for a in records):
            records.append(_record(role, signer))
    _write_trust(trust_path, records)
    AuthorityLedger(storage / "AUTHORITY_LEDGER.jsonl")
    registry = AuthorityRegistry.load(trust_path)
    print(json.dumps({
        "status": "provisioned",
        "storage": str(storage),
        "roles": {r.role: r.key_id for r in registry._by_key.values()},
        "note": "single-host provisioning is a development convenience; "
                "production deployments must separate role key custody"},
          indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
